declare module 'three'
declare module 'three/examples/jsm/loaders/GLTFLoader.js'
declare module 'three/examples/jsm/controls/OrbitControls.js'
declare module 'dat.gui'
declare module 'three/examples/jsm/objects/Reflector.js'